/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-06-18 06:45:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<!-- Required meta tags-->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"au theme template\">\r\n");
      out.write("<meta name=\"author\" content=\"Hau Nguyen\">\r\n");
      out.write("<meta name=\"keywords\" content=\"au theme template\">\r\n");
      out.write("\r\n");
      out.write("<!-- Title Page-->\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Fontfaces CSS-->\r\n");
      out.write("<link href=\"css/font-face.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"vendor/font-awesome-4.7/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"vendor/font-awesome-5/css/fontawesome-all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"vendor/mdi-font/css/material-design-iconic-font.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS-->\r\n");
      out.write("<link href=\"vendor/bootstrap-4.1/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Vendor CSS-->\r\n");
      out.write("<link href=\"vendor/animsition/animsition.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"vendor/wow/animate.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"vendor/css-hamburgers/hamburgers.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\tmedia=\"all\">\r\n");
      out.write("<link href=\"vendor/slick/slick.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"vendor/select2/select2.min.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<link href=\"vendor/perfect-scrollbar/perfect-scrollbar.css\"\r\n");
      out.write("\trel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main CSS-->\r\n");
      out.write("<link href=\"css/theme.css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction validateForm() {\r\n");
      out.write("\t\tvar x = document.forms[\"loginForm\"][\"userName\", \"password\"].value;\r\n");
      out.write("\t\tif (x == \"\") {\r\n");
      out.write("\t\t\talert(\"Please Enter User Name and Password both\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"animsition\">\r\n");
      out.write("\t<div class=\"page-wrapper\">\r\n");
      out.write("\t\t<div class=\"page-content--bge5\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"login-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"login-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"> <img src=\"images/icon/logo.png\" alt=\"CoolAdmin\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"login-form\">\r\n");
      out.write("\t\t\t\t\t\t\t<form name=loginForm action=\"LoginServlet\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonsubmit=\"return validateForm()\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>User Name</label> <input class=\"au-input au-input--full\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" name=\"userName\" placeholder=\"User Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label>Password</label> <input class=\"au-input au-input--full\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"password\" name=\"password\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login-checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label> <input type=\"checkbox\" name=\"remember\">Remember\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tMe\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"au-btn au-btn--block au-btn--green m-b-20\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"submit\">sign in</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<font color=red> ");
			
                                 	Object message = request.getAttribute("message");
 									if(message== null)
 									{
 										out.println("");
 									} else
									out.println(message);
 									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"register-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tDon't you have account? <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"http://localhost:8080/funbook_app/register.jsp\">Sign\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tUp Here</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Jquery JS-->\r\n");
      out.write("\t<script src=\"vendor/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap JS-->\r\n");
      out.write("\t<script src=\"vendor/bootstrap-4.1/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/bootstrap-4.1/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Vendor JS       -->\r\n");
      out.write("\t<script src=\"vendor/slick/slick.min.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"vendor/wow/wow.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/animsition/animsition.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/bootstrap-progressbar/bootstrap-progressbar.min.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"vendor/counter-up/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/counter-up/jquery.counterup.min.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"vendor/circle-progress/circle-progress.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/perfect-scrollbar/perfect-scrollbar.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/chartjs/Chart.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"vendor/select2/select2.min.js\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Main JS-->\r\n");
      out.write("\t<script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
